sensors:
  thermistors:
    T1: 0
    T2: 1
    T3: 2
    fluid_in: 3
    fluid_out: 4
  pressure:
    in: 5
    out: 6
  heater_power: 7 # Optional
  pump_power: 8 # Optional

calibration:
  thermistor:
    R_fixed: 51000.0 # Fixed resistor value in ohms
    R_nominal: 100000.0 # Thermistor nominal resistance at 25C (ohms)
    T_nominal: 25.0 # Nominal temperature (°C)
    beta: 3950.0 # Beta coefficient
    adc_max: 1023.0 # ADC max reading (10-bit)
  pressure_scale: 0.1 # volts to bar
  voltage_ref: 3.3
  adc_max: 1023
  flow_rate_m3s: 0.0001 # Optional: used in pump power calc if not dynamically measured

geometry: "flat_fins" # Optional: label for grouping runs by exchanger design
