calibration:
  V_ref: 5
  adc_max: 1023
  flow_rate_m3s: 6.66667e-06
  heater_power: 200
  pressure_transducer:
    P_max: 200
    P_min: 0
    V_max: 4.5
    V_min: 0
    V_ref: 5
    adc_max: 1023.0
  pump_power: 4.88
  thermistor:
    R_fixed: 100000.0
    R_nominal: 100000.0
    T_nominal: 25.0
    adc_max: 1023.0
    beta: -19625.0
flow_rate_m3s: 40.0
geometry: simple_fins
sensors:
  heater_power: None
  pressure:
    P_in: 4
    P_out: 3
  pump_power: None
  thermistors:
    T1: 2
    T2: 0
    T3: 1
    fluid_in: 6
    fluid_out: 5
