sensors:
  thermistors:
    T1: 0
    T2: 1
    T3: 2
    fluid_in: None # 5
    fluid_out: None # 6
  pressure:
    P_in: 3
    P_out: 4
  heater_power: 5 # Optional, originally none
  pump_power: 6 # Optional, originally none

calibration:
  thermistor:
    R_fixed: 100000.0 # Fixed resistor value in ohms
    R_nominal: 100000.0 # Thermistor nominal resistance at 25C (ohms)
    T_nominal: 25.0 # Nominal temperature (°C)
    beta: -19625.0 # Beta coefficient, 3950.0, beta value is ok now dont change
    adc_max: 1023.0 # ADC max reading (10-bit)
  pressure_transducer:
    V_min: 0 # V
    P_min: 0 # PSI | Lowest reading @ V_0
    V_max: 4.5 # V
    P_max: 200 # PSI | Highest reading @ V_max
    V_ref: 5
    adc_max: 1023.0
  # pressure_scale: 0.1 # volts to bar
  V_ref: 5
  adc_max: 1023
  flow_rate_m3s: 0.00000666667 # Optional: used in pump power calc if not dynamically measured

geometry: "simple_fins" # Optional: label for grouping runs by exchanger design
