sensors:
  thermistors:
    T1: 0
    T2: 1
    T3: 2
    fluid_in: 3
    fluid_out: 4
  pressure:
    in: 5
    out: 6
  heater_power: 7 # Optional
  pump_power: 8 # Optional

calibration:
  thermistor:
    R0: 10000
    T0: 298.16
    B: 3950
  pressure_scale: 0.1 # volts to bar
  voltage_ref: 3.3
